livrederecettes_homepage:
    pattern:  /
    defaults: { _controller: FDLivrederecettesBundle:Livrederecettes:homepage }

# SHOPPING LIST section
livrederecettes_listShoppingLists:
    pattern:  /listShoppingLists
    defaults: { _controller: FDLivrederecettesBundle:ShoppingList:listShoppingLists }
    
livrederecettes_viewShoppingList:
    pattern:  /viewShoppingList/{id}
    defaults: { _controller: FDLivrederecettesBundle:ShoppingList:viewShoppingList }
    requirements:
                  id: \d+

livrederecettes_addShoppingList:
    pattern:  /addShoppingList
    defaults: { _controller: FDLivrederecettesBundle:ShoppingList:addShoppingList }

livrederecettes_modifyShoppingList:
    pattern:  /modifyShoppingList/{id}
    defaults: { _controller: FDLivrederecettesBundle:ShoppingList:modifyShoppingList }
    requirements:
                  id: \d+
    
livrederecettes_deleteShoppingList:
    pattern:  /deleteShoppingList/{id}
    defaults: { _controller: FDLivrederecettesBundle:ShoppingList:deleteShoppingList }
    requirements:
                  id: \d+

livrederecettes_generateShoppingList:
    pattern: /generateShoppingList/{menuId}
    defaults: { _controller: FDLivrederecettesBundle:ShoppingList:generateShoppingList }
    requirements:
                  id: \d+

# MENU section
livrederecettes_listMenus:
    pattern:  /listMenus
    defaults: { _controller: FDLivrederecettesBundle:Menu:listMenus }
    
livrederecettes_viewMenu:
    pattern:  /viewMenu/{id}
    defaults: { _controller: FDLivrederecettesBundle:Menu:viewMenu }
    requirements:
                  id: \d+

livrederecettes_addMenu:
    pattern:  /addMenu
    defaults: { _controller: FDLivrederecettesBundle:Menu:addMenu }

livrederecettes_modifyMenu:
    pattern:  /modifyMenu/{id}
    defaults: { _controller: FDLivrederecettesBundle:Menu:modifyMenu }
    requirements:
                  id: \d+
    
livrederecettes_deleteMenu:
    pattern:  /deleteMenu/{id}
    defaults: { _controller: FDLivrederecettesBundle:Menu:deleteMenu }
    requirements:
                  id: \d+

# RECIPE section

livrederecettes_listRecipies:
    pattern:  /listRecipies
    defaults: { _controller: FDLivrederecettesBundle:Recipe:listRecipies }
    
livrederecettes_viewRecipe:
    pattern:  /viewRecipe/{id}
    defaults: { _controller: FDLivrederecettesBundle:Recipe:viewRecipe }
    requirements:
                  id: \d+

livrederecettes_addRecipe:
    pattern:  /addRecipe
    defaults: { _controller: FDLivrederecettesBundle:Recipe:addRecipe }

livrederecettes_modifyRecipe:
    pattern:  /modifyRecipe/{id}
    defaults: { _controller: FDLivrederecettesBundle:Recipe:modifyRecipe }
    requirements:
                  id: \d+
    
livrederecettes_deleteRecipe:
    pattern:  /deleteRecipe/{id}
    defaults: { _controller: FDLivrederecettesBundle:Recipe:deleteRecipe }
    requirements:
                  id: \d+

# PRODUCT section
livrederecettes_listProducts:
    pattern:  /listProducts
    defaults: { _controller: FDLivrederecettesBundle:Product:listProducts }

livrederecettes_viewProduct:
    pattern:  /viewProduct/{id}
    defaults: { _controller: FDLivrederecettesBundle:Product:viewProduct }
    requirements:
                  id: \d+
    
livrederecettes_addProduct:
    pattern:  /addProduct
    defaults: { _controller: FDLivrederecettesBundle:Product:addProduct }
    
livrederecettes_modifyProduct:
    pattern:  /modifyProduct/{id}
    defaults: { _controller: FDLivrederecettesBundle:Product:modifyProduct }
    requirements:
                  id: \d+
    
livrederecettes_deleteProduct:
    pattern:  /deleteProduct/{id}
    defaults: { _controller: FDLivrederecettesBundle:Product:deleteProduct }
    requirements:
                  id: \d+

# INGREDIENT section
livrederecettes_listIngredients:
    pattern:  /listIngredients
    defaults: { _controller: FDLivrederecettesBundle:Livrederecettes:homepage }

livrederecettes_viewIngredient:
    pattern:  /viewIngredient/{id}
    defaults: { _controller: FDLivrederecettesBundle:Livrederecettes:homepage }
    requirements:
                  id: \d+
    
livrederecettes_addIngredient:
    pattern:  /addIngredient
    defaults: { _controller: FDLivrederecettesBundle:Livrederecettes:homepage }
    
livrederecettes_modifyIngredient:
    pattern:  /modifyIngredient
    defaults: { _controller: FDLivrederecettesBundle:Livrederecettes:homepage }
    
livrederecettes_deleteIngredient:
    pattern:  /deleteIngredient
    defaults: { _controller: FDLivrederecettesBundle:Livrederecettes:homepage }

# UNIT section
livrederecettes_listUnits:
  pattern: /listUnits
  defaults: { _controller: FDLivrederecettesBundle:Unit:listUnits }

livrederecettes_viewUnit:
    pattern:  /viewUnit/{id}
    defaults: { _controller: FDLivrederecettesBundle:Unit:viewUnit }
    requirements:
                  id: \d+

livrederecettes_addUnit:
    pattern:  /addUnit
    defaults: { _controller: FDLivrederecettesBundle:Unit:addUnit }
    
livrederecettes_modifyUnit:
    pattern:  /modifyUnit/{id}
    defaults: { _controller: FDLivrederecettesBundle:Unit:modifyUnit }
    requirements:
                  id: \d+
    
livrederecettes_deleteUnit:
    pattern:  /deleteUnit/{id}
    defaults: { _controller: FDLivrederecettesBundle:Unit:deleteUnit }
    requirements:
                  id:  \d+
    
# PRODUCTTYPE section
livrederecettes_listProductTypes:
  pattern: /listProductTypes
  defaults: { _controller: FDLivrederecettesBundle:ProductType:listProductTypes }

livrederecettes_viewProductType:
    pattern:  /viewProductType/{id}
    defaults: { _controller: FDLivrederecettesBundle:ProductType:viewProductType }
    requirements:
                  id: \d+

livrederecettes_addProductType:
    pattern:  /addProductType
    defaults: { _controller: FDLivrederecettesBundle:ProductType:addProductType }
    
livrederecettes_modifyProductType:
    pattern:  /modifyProductType/{id}
    defaults: { _controller: FDLivrederecettesBundle:ProductType:modifyProductType }
    requirements:
                  id:  \d+
    
livrederecettes_deleteProductType:
    pattern:  /deleteProductType/{id}
    defaults: { _controller: FDLivrederecettesBundle:ProductType:deleteProductType }
    requirements:
                  id:  \d+
                  
# MEALTYPE section
livrederecettes_listMealTypes:
    pattern:  /listMealTypes
    defaults: { _controller: FDLivrederecettesBundle:MealType:listMealTypes }
    
livrederecettes_viewMealType:
    pattern:  /viewMealType/{id}
    defaults: { _controller: FDLivrederecettesBundle:MealType:viewMealType }
    requirements:
                  id: \d+

livrederecettes_addMealType:
    pattern:  /addMealType
    defaults: { _controller: FDLivrederecettesBundle:MealType:addMealType }

livrederecettes_modifyMealType:
    pattern:  /modifyMealType/{id}
    defaults: { _controller: FDLivrederecettesBundle:MealType:modifyMealType }
    requirements:
                  id: \d+
    
livrederecettes_deleteMealType:
    pattern:  /deleteMealType/{id}
    defaults: { _controller: FDLivrederecettesBundle:MealType:deleteMealType }
    requirements:
                  id: \d+