parameters:
#    fd_livrederecettes.example.class: FD\LivrederecettesBundle\Example

services:
#    fd_livrederecettes.example:
#        class: %fd_livrederecettes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
