<?php

namespace FD\LivrederecettesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{
    public function getIngredientsByUnit($unit_id)
    {
        $queryBuilder = $this->createQueryBuilder('i');
        
        $queryBuilder->where('i.unit = :v_unit')
                ->setParameter('v_unit', $unit_id);
        
        return $queryBuilder->getQuery()->getResult();
    }
    
    public function getIngredientsByProduct($product_id)
    {
        $queryBuilder = $this->createQueryBuilder('i');
        
        $queryBuilder->where('i.product = :v_product')
                ->setParameter('v_unit', $product_id);
        
        return $queryBuilder->getQuery()->getResult();
    }
    
}
