<?php

namespace FD\LivrederecettesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MealTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealTypeRepository extends EntityRepository
{
}
