<?php

namespace FD\LivrederecettesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends EntityRepository
{
    public function getMealByType($mealtype_id)
    {
        $queryBuilder = $this->createQueryBuilder('m');
        
        $queryBuilder->where('m.mealType = :v_mealtype')
                ->setParameter('v_mealtype', $mealtype_id);
        
        return $queryBuilder->getQuery()->getResult();
    }
}
