<?php

namespace FD\LivrederecettesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductsByType($producttype_id)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        
        $queryBuilder->where('p.producttype = :v_producttype')
                ->setParameter('v_producttype', $producttype_id);
        
        return $queryBuilder->getQuery()->getResult();
    }
}
