<?php

namespace FD\LivrederecettesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository {
    
    public function getTop3Recipe()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
                                  ->select('r')
                                  ->from($this->_entityName, 'r')
                                  ->setMaxResults(3);
        $queryBuilder->orderBy('r.id', 'DESC');
        
        
        return $queryBuilder->getQuery()->getResult();
    }
    
}
