<?php

namespace FD\LivrederecettesBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MenuController__JMSInjector
{
    public static function inject($container) {
        $instance = new \FD\LivrederecettesBundle\Controller\MenuController();
        return $instance;
    }
}
